### ISSUE TITLE
Team discussion comments are white

### ISSUE THREAD

**Issue by nmoinvaz** [poychang/github-dark-theme#137]
It appears that the Team discussion comments are white. The css class is `timeline-inline-comments`.

**Comment by wangkanai** [comment]
![image](https://user-images.githubusercontent.com/10666633/75417427-997d9500-5963-11ea-88e9-045ddf45cbdf.png)

I think we have the same issue.

**Comment by wangkanai** [comment]
For your information
```css
.notifications-list-item:hover {
    background-color: #f1f8ff!important;
}
```
Refer: https://github.githubassets.com/app/app/assets/stylesheets/custom/github/notifications-v2.scss
