### ISSUE TITLE
Change scrollbar theme

### ISSUE THREAD

**Issue by poychang** [poychang/github-dark-theme#29]
Like the picture below, it changes default scrollbar theme by custom CSS.

Anyone has any ideal about this?

```css
::-webkit-scrollbar {
    width: 8px;
}
::-webkit-scrollbar-track {
    -webkit-border-radius: 10px;
    border-radius: 10px;
    margin: 0 0 8px 0;
}
::-webkit-scrollbar-thumb {
    -webkit-border-radius: 4px;
    border-radius: 4px;
    background: rgb(219, 219, 219);
}
```
 
![image](https://user-images.githubusercontent.com/4879879/58393132-cec12380-806f-11e9-84e1-55ef26b75a2b.png)
