### ISSUE TITLE
Notification pages styling needs updating 

### ISSUE THREAD

**Issue by guidezpl** [poychang/github-dark-theme#305]
<img width="583" alt="Screenshot 2020-11-18 at 09 31 02" src="https://user-images.githubusercontent.com/6655696/99505219-d4f04180-2980-11eb-8e47-7252a27759f4.png">

**Comment by RymRabehi** [comment]
I confirm, I have the same issue.

**Comment by DeividasJackus** [comment]
Confirmed having same issue from today.

**Comment by Ali-RS** [comment]
Same issue.

**Comment by foss-** [comment]
Just use the "Thumbs up" if you are affected by this (guess all users are). No need for a reply which triggers notifications which add no value. Thanks.

**Comment by iProdigy** [comment]
Relevant `notifications-v2.scss` snippet causing this issue:
```scss
.notifications-list-item.notification-archived, .notifications-list-item.notification-read {
    background-color: var(--color-notifications-row-read-bg)!important;
}
```
