### ISSUE TITLE
White background on main activity list

### ISSUE THREAD

**Issue by oscargm** [poychang/github-dark-theme#74]
Extension show activity container with white background in [github main page](https://github.com/): 
![Screenshot_20191103_205426](https://user-images.githubusercontent.com/3372617/68091123-2a43d880-fe7c-11e9-9f19-b03b58b1fed5.png)
Styles applied to the section:

```css
.dashboard .js-all-activity-header + div {
    background-color: #FFF;
	border: 1px solid #d1d5da;
    border-radius: 3px;
    margin-top: 8px !important;
}
```
I understand that this styles should be overridden somewhere in the configuration files, but don't know where excactly

Firefox 70.0.1 on linux
